<?php 
$this->load->view('frontend/beranda/slider');
$this->load->view('frontend/beranda/statistic');
$this->load->view('frontend/beranda/berita');
$this->load->view('frontend/beranda/kisah');
$this->load->view('frontend/beranda/kenal');
$this->load->view('frontend/beranda/mitra');
$this->load->view('frontend/beranda/tanya');
?>